wandb_version: 1

activation_func:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 5
hidden_layer_size:
  value: 128
hidden_layers:
  value: 4
learning_rate:
  value: 0.0001
loss_fn:
  value: cross_entropy
optimizer:
  value: rmsprop
weight_decay:
  value: 0
weight_init:
  value: random_init
