wandb_version: 1

activation_func:
  value: tanh
batch_size:
  value: 128
epochs:
  value: 10
hidden_layer_size:
  value: 128
hidden_layers:
  value: 5
learning_rate:
  value: 0.0001
loss_fn:
  value: cross_entropy
optimizer:
  value: sgd
weight_decay:
  value: 0.0005
weight_init:
  value: random_init
