_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.9.12
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
                - 105
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
                - 105
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.9.12
            "5": 0.19.8
            "8":
                - 5
            "10":
                - 3
            "12": 0.19.8
            "13": linux-x86_64
activation_func:
    value: sigmoid
batch_size:
    value: 64
epochs:
    value: 10
hidden_layer_size:
    value: 32
hidden_layers:
    value: 4
learning_rate:
    value: 0.001
loss_fn:
    value: cross_entropy
optimizer:
    value: nadam
weight_decay:
    value: 0.0005
weight_init:
    value: xavier_init
