wandb_version: 1

activation_func:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 5
hidden_layer_size:
  value: 32
hidden_layers:
  value: 5
learning_rate:
  value: 0.0001
loss_fn:
  value: cross_entropy
optimizer:
  value: nag
weight_decay:
  value: 0.0005
weight_init:
  value: xavier_init
